name: "Update GitHub mirror repository"
on:
  schedule:
    - cron: "0 12 * * *" # Run every day at noon.
  workflow_dispatch:
  push:
jobs:
  update-mirror:
    name: "update mirror by pulling latest commit from codeberg"
    runs-on: ubuntu-latest
    steps:
      - 
        name: preparing environment
        run: sudo apt --quiet update --yes && sudo apt --quiet upgrade --yes
      - 
        name: clone repository from codeberg
        run: git clone https://codeberg.org/teddit/teddit.git
      - 
        name: list directory contents
        run: cd teddit && ls -lisha
      - 
        name: change remote origin to GitHub remote repository
        run: cd teddit && git remote set-url origin https://github.com/eUgEntOptIc44/teddit.git # change url and add PAT for authentification
      -
        name: force push contents to GitHub remote
        run: cd teddit && git push origin -f
